management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
   
  metrics:
    export: 
      azuremonitor:
        instrumentation-key=f9e62871-38ef-4f6f-ba40-882ada0261a3
azure:
  application-insights:
    instrumentation-key=f9e62871-38ef-4f6f-ba40-882ada0261a3
spring:
  h2:
    console.enabled: true
  